syntax = "proto3";
package kratos.api;

option go_package = "github.com/velonyapp/asset/internal/conf";

import "buf/validate/validate.proto";
import "google/protobuf/duration.proto";

message Bootstrap {
  Service service = 1 [
    (buf.validate.field).required = true
  ];
  Transport     transport     = 2 [
    (buf.validate.field).required = true
  ];
  Data          data          = 3 [
    (buf.validate.field).required = true
  ];
  Observability observability = 4;
}

message Service {
  string public_url = 1 [
    (buf.validate.field).string.uri = true
  ];

  string upload_token_secret = 2 [
    (buf.validate.field).string.min_len = 32
  ];
}

message Transport {
  message HTTP {
    string address = 1 [
      (buf.validate.field).string.host_and_port = true
    ];

    google.protobuf.Duration timeout = 2 [
      (buf.validate.field).duration.gt = {}
    ];
  }

  message GRPC {
    string address = 1 [
      (buf.validate.field).string.host_and_port = true
    ];

    google.protobuf.Duration timeout = 2 [
      (buf.validate.field).duration.gt = {}
    ];
  }

  HTTP http = 1 [
    (buf.validate.field).required = true
  ];
  GRPC grpc = 2 [
    (buf.validate.field).required = true
  ];
}

message Data {
  message S3 {
    string endpoint = 1 [
      (buf.validate.field).string.min_len = 1
    ];
    string access_key_id = 2 [
      (buf.validate.field).string.min_len = 1
    ];
    string secret_access_key = 3 [
      (buf.validate.field).string.min_len = 1
    ];

    string bucket = 4 [
      (buf.validate.field).string.min_len = 1
    ];
  }

  S3 s3 = 1 [
    (buf.validate.field).required = true
  ];
}

message Observability {
  enum Protocol {
    PROTOCOL_UNSPECIFIED   = 0;
    PROTOCOL_GRPC          = 1;
    PROTOCOL_HTTP_PROTOBUF = 2;
  }

  message Tracing {
    Protocol protocol = 1 [
      (buf.validate.field).enum = { defined_only: true, not_in: [0] }
    ];
    string endpoint = 2 [
      (buf.validate.field).string.min_len = 1
    ];
    optional string authorization = 3 [
      (buf.validate.field).string.min_len = 1
    ];

    optional double sample_ratio = 4 [
      (buf.validate.field).double = { gte: 0.0, lte: 1.0 }
    ];
  }

  message Metrics {
    Protocol protocol = 1 [
      (buf.validate.field).enum = { defined_only: true, not_in: [0] }
    ];
    string endpoint = 2 [
      (buf.validate.field).string.min_len = 1
    ];
    optional string authorization = 3 [
      (buf.validate.field).string.min_len = 1
    ];

    google.protobuf.Duration export_interval = 4 [
      (buf.validate.field).required = true,
      (buf.validate.field).duration.gt = {}
    ];
  }

  Tracing tracing = 1;
  Metrics metrics = 2;
}
