// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Telemetry_Protocol int32

const (
	Telemetry_PROTOCOL_UNSPECIFIED Telemetry_Protocol = 0
	Telemetry_GRPC                 Telemetry_Protocol = 1
	Telemetry_HTTP_PROTOBUF        Telemetry_Protocol = 2
)

// Enum value maps for Telemetry_Protocol.
var (
	Telemetry_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "GRPC",
		2: "HTTP_PROTOBUF",
	}
	Telemetry_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"GRPC":                 1,
		"HTTP_PROTOBUF":        2,
	}
)

func (x Telemetry_Protocol) Enum() *Telemetry_Protocol {
	p := new(Telemetry_Protocol)
	*p = x
	return p
}

func (x Telemetry_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Telemetry_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Telemetry_Protocol) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Telemetry_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Telemetry_Protocol.Descriptor instead.
func (Telemetry_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     *Transport             `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Telemetry     *Telemetry             `protobuf:"bytes,3,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Transport_HTTP        `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Transport_GRPC        `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Rabbitmq      *Transport_RabbitMQ    `protobuf:"bytes,3,opt,name=rabbitmq,proto3" json:"rabbitmq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetHttp() *Transport_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Transport) GetGrpc() *Transport_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Transport) GetRabbitmq() *Transport_RabbitMQ {
	if x != nil {
		return x.Rabbitmq
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mysql         *Data_MySQL            `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	S3            *Data_S3               `protobuf:"bytes,2,opt,name=s3,proto3" json:"s3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMysql() *Data_MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetS3() *Data_S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracing       *Telemetry_Tracing     `protobuf:"bytes,1,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics       *Telemetry_Metrics     `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Telemetry) GetTracing() *Telemetry_Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Telemetry) GetMetrics() *Telemetry_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Transport_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_HTTP) Reset() {
	*x = Transport_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_HTTP) ProtoMessage() {}

func (x *Transport_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_HTTP.ProtoReflect.Descriptor instead.
func (*Transport_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transport_HTTP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Transport_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_GRPC) Reset() {
	*x = Transport_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_GRPC) ProtoMessage() {}

func (x *Transport_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_GRPC.ProtoReflect.Descriptor instead.
func (*Transport_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Transport_GRPC) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Transport_RabbitMQ struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Address       string                     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                     `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                     `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Queues        *Transport_RabbitMQ_Queues `protobuf:"bytes,4,opt,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_RabbitMQ) Reset() {
	*x = Transport_RabbitMQ{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_RabbitMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_RabbitMQ) ProtoMessage() {}

func (x *Transport_RabbitMQ) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_RabbitMQ.ProtoReflect.Descriptor instead.
func (*Transport_RabbitMQ) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Transport_RabbitMQ) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_RabbitMQ) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Transport_RabbitMQ) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Transport_RabbitMQ) GetQueues() *Transport_RabbitMQ_Queues {
	if x != nil {
		return x.Queues
	}
	return nil
}

type Transport_RabbitMQ_Queues struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreateImage        string                 `protobuf:"bytes,1,opt,name=create_image,json=createImage,proto3" json:"create_image,omitempty"`
	ConfirmImageUpload string                 `protobuf:"bytes,2,opt,name=confirm_image_upload,json=confirmImageUpload,proto3" json:"confirm_image_upload,omitempty"`
	ProcessImage       string                 `protobuf:"bytes,3,opt,name=process_image,json=processImage,proto3" json:"process_image,omitempty"`
	DeleteImage        string                 `protobuf:"bytes,4,opt,name=delete_image,json=deleteImage,proto3" json:"delete_image,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Transport_RabbitMQ_Queues) Reset() {
	*x = Transport_RabbitMQ_Queues{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_RabbitMQ_Queues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_RabbitMQ_Queues) ProtoMessage() {}

func (x *Transport_RabbitMQ_Queues) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_RabbitMQ_Queues.ProtoReflect.Descriptor instead.
func (*Transport_RabbitMQ_Queues) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *Transport_RabbitMQ_Queues) GetCreateImage() string {
	if x != nil {
		return x.CreateImage
	}
	return ""
}

func (x *Transport_RabbitMQ_Queues) GetConfirmImageUpload() string {
	if x != nil {
		return x.ConfirmImageUpload
	}
	return ""
}

func (x *Transport_RabbitMQ_Queues) GetProcessImage() string {
	if x != nil {
		return x.ProcessImage
	}
	return ""
}

func (x *Transport_RabbitMQ_Queues) GetDeleteImage() string {
	if x != nil {
		return x.DeleteImage
	}
	return ""
}

type Data_MySQL struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dsn                   string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxOpenConnections    *uint32                `protobuf:"varint,2,opt,name=max_open_connections,json=maxOpenConnections,proto3,oneof" json:"max_open_connections,omitempty"`
	MaxIdleConnections    *uint32                `protobuf:"varint,3,opt,name=max_idle_connections,json=maxIdleConnections,proto3,oneof" json:"max_idle_connections,omitempty"`
	MaxConnectionLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_connection_lifetime,json=maxConnectionLifetime,proto3" json:"max_connection_lifetime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Data_MySQL) Reset() {
	*x = Data_MySQL{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MySQL) ProtoMessage() {}

func (x *Data_MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MySQL.ProtoReflect.Descriptor instead.
func (*Data_MySQL) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_MySQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_MySQL) GetMaxOpenConnections() uint32 {
	if x != nil && x.MaxOpenConnections != nil {
		return *x.MaxOpenConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxIdleConnections() uint32 {
	if x != nil && x.MaxIdleConnections != nil {
		return *x.MaxIdleConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxConnectionLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnectionLifetime
	}
	return nil
}

type Data_S3 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Bucket          string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_S3) Reset() {
	*x = Data_S3{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_S3) ProtoMessage() {}

func (x *Data_S3) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_S3.ProtoReflect.Descriptor instead.
func (*Data_S3) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_S3) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Data_S3) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *Data_S3) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *Data_S3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type Telemetry_Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Telemetry_Protocol     `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Telemetry_Protocol" json:"protocol,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	SampleRatio   *float64               `protobuf:"fixed64,4,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry_Tracing) Reset() {
	*x = Telemetry_Tracing{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry_Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry_Tracing) ProtoMessage() {}

func (x *Telemetry_Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry_Tracing.ProtoReflect.Descriptor instead.
func (*Telemetry_Tracing) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Telemetry_Tracing) GetProtocol() Telemetry_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Telemetry_PROTOCOL_UNSPECIFIED
}

func (x *Telemetry_Tracing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Telemetry_Tracing) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Telemetry_Tracing) GetSampleRatio() float64 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

type Telemetry_Metrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       Telemetry_Protocol     `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Telemetry_Protocol" json:"protocol,omitempty"`
	Endpoint       string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization  *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	ExportInterval *durationpb.Duration   `protobuf:"bytes,4,opt,name=export_interval,json=exportInterval,proto3" json:"export_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Telemetry_Metrics) Reset() {
	*x = Telemetry_Metrics{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry_Metrics) ProtoMessage() {}

func (x *Telemetry_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry_Metrics.ProtoReflect.Descriptor instead.
func (*Telemetry_Metrics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Telemetry_Metrics) GetProtocol() Telemetry_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Telemetry_PROTOCOL_UNSPECIFIED
}

func (x *Telemetry_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Telemetry_Metrics) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Telemetry_Metrics) GetExportInterval() *durationpb.Duration {
	if x != nil {
		return x.ExportInterval
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\xab\x01\n" +
	"\tBootstrap\x12;\n" +
	"\ttransport\x18\x01 \x01(\v2\x15.kratos.api.TransportB\x06\xbaH\x03\xc8\x01\x01R\ttransport\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataB\x06\xbaH\x03\xc8\x01\x01R\x04data\x123\n" +
	"\ttelemetry\x18\x03 \x01(\v2\x15.kratos.api.TelemetryR\ttelemetry\"\xa2\x06\n" +
	"\tTransport\x126\n" +
	"\x04http\x18\x01 \x01(\v2\x1a.kratos.api.Transport.HTTPB\x06\xbaH\x03\xc8\x01\x01R\x04http\x126\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1a.kratos.api.Transport.GRPCB\x06\xbaH\x03\xc8\x01\x01R\x04grpc\x12B\n" +
	"\brabbitmq\x18\x03 \x01(\v2\x1e.kratos.api.Transport.RabbitMQB\x06\xbaH\x03\xc8\x01\x01R\brabbitmq\x1ai\n" +
	"\x04HTTP\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x1ai\n" +
	"\x04GRPC\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x1a\x8a\x03\n" +
	"\bRabbitMQ\x12!\n" +
	"\aaddress\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aaddress\x12#\n" +
	"\busername\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpassword\x12E\n" +
	"\x06queues\x18\x04 \x01(\v2%.kratos.api.Transport.RabbitMQ.QueuesB\x06\xbaH\x03\xc8\x01\x01R\x06queues\x1a\xc9\x01\n" +
	"\x06Queues\x12*\n" +
	"\fcreate_image\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vcreateImage\x129\n" +
	"\x14confirm_image_upload\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x12confirmImageUpload\x12,\n" +
	"\rprocess_image\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fprocessImage\x12*\n" +
	"\fdelete_image\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdeleteImage\"\x8c\x06\n" +
	"\x04Data\x124\n" +
	"\x05mysql\x18\x01 \x01(\v2\x16.kratos.api.Data.MySQLB\x06\xbaH\x03\xc8\x01\x01R\x05mysql\x12+\n" +
	"\x02s3\x18\x02 \x01(\v2\x13.kratos.api.Data.S3B\x06\xbaH\x03\xc8\x01\x01R\x02s3\x1a\xf1\x03\n" +
	"\x05MySQL\x12\x19\n" +
	"\x03dsn\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03dsn\x125\n" +
	"\x14max_open_connections\x18\x02 \x01(\rH\x00R\x12maxOpenConnections\x88\x01\x01\x125\n" +
	"\x14max_idle_connections\x18\x03 \x01(\rH\x01R\x12maxIdleConnections\x88\x01\x01\x12[\n" +
	"\x17max_connection_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x022\x00R\x15maxConnectionLifetime:\xcf\x01\xbaH\xcb\x01\x1a\xc8\x01\n" +
	"\x11mysql.pool_limits\x12Xmax_idle_connections cannot exceed max_open_connections unless max_open_connections is 0\x1aYthis.max_open_connections == 0u || this.max_idle_connections <= this.max_open_connectionsB\x17\n" +
	"\x15_max_open_connectionsB\x17\n" +
	"\x15_max_idle_connections\x1a\xac\x01\n" +
	"\x02S3\x12#\n" +
	"\bendpoint\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x12+\n" +
	"\raccess_key_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaccessKeyId\x123\n" +
	"\x11secret_access_key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fsecretAccessKey\x12\x1f\n" +
	"\x06bucket\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06bucket\"\xe1\x05\n" +
	"\tTelemetry\x127\n" +
	"\atracing\x18\x01 \x01(\v2\x1d.kratos.api.Telemetry.TracingR\atracing\x127\n" +
	"\ametrics\x18\x02 \x01(\v2\x1d.kratos.api.Telemetry.MetricsR\ametrics\x1a\x8e\x02\n" +
	"\aTracing\x12F\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1e.kratos.api.Telemetry.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12?\n" +
	"\fsample_ratio\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\vsampleRatio\x88\x01\x01B\x10\n" +
	"\x0e_authorizationB\x0f\n" +
	"\r_sample_ratio\x1a\x8d\x02\n" +
	"\aMetrics\x12F\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1e.kratos.api.Telemetry.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12O\n" +
	"\x0fexport_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x0eexportIntervalB\x10\n" +
	"\x0e_authorization\"A\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\x11\n" +
	"\rHTTP_PROTOBUF\x10\x02B*Z(github.com/velonyapp/asset/internal/confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_conf_conf_proto_goTypes = []any{
	(Telemetry_Protocol)(0),           // 0: kratos.api.Telemetry.Protocol
	(*Bootstrap)(nil),                 // 1: kratos.api.Bootstrap
	(*Transport)(nil),                 // 2: kratos.api.Transport
	(*Data)(nil),                      // 3: kratos.api.Data
	(*Telemetry)(nil),                 // 4: kratos.api.Telemetry
	(*Transport_HTTP)(nil),            // 5: kratos.api.Transport.HTTP
	(*Transport_GRPC)(nil),            // 6: kratos.api.Transport.GRPC
	(*Transport_RabbitMQ)(nil),        // 7: kratos.api.Transport.RabbitMQ
	(*Transport_RabbitMQ_Queues)(nil), // 8: kratos.api.Transport.RabbitMQ.Queues
	(*Data_MySQL)(nil),                // 9: kratos.api.Data.MySQL
	(*Data_S3)(nil),                   // 10: kratos.api.Data.S3
	(*Telemetry_Tracing)(nil),         // 11: kratos.api.Telemetry.Tracing
	(*Telemetry_Metrics)(nil),         // 12: kratos.api.Telemetry.Metrics
	(*durationpb.Duration)(nil),       // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	2,  // 0: kratos.api.Bootstrap.transport:type_name -> kratos.api.Transport
	3,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 2: kratos.api.Bootstrap.telemetry:type_name -> kratos.api.Telemetry
	5,  // 3: kratos.api.Transport.http:type_name -> kratos.api.Transport.HTTP
	6,  // 4: kratos.api.Transport.grpc:type_name -> kratos.api.Transport.GRPC
	7,  // 5: kratos.api.Transport.rabbitmq:type_name -> kratos.api.Transport.RabbitMQ
	9,  // 6: kratos.api.Data.mysql:type_name -> kratos.api.Data.MySQL
	10, // 7: kratos.api.Data.s3:type_name -> kratos.api.Data.S3
	11, // 8: kratos.api.Telemetry.tracing:type_name -> kratos.api.Telemetry.Tracing
	12, // 9: kratos.api.Telemetry.metrics:type_name -> kratos.api.Telemetry.Metrics
	13, // 10: kratos.api.Transport.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 11: kratos.api.Transport.GRPC.timeout:type_name -> google.protobuf.Duration
	8,  // 12: kratos.api.Transport.RabbitMQ.queues:type_name -> kratos.api.Transport.RabbitMQ.Queues
	13, // 13: kratos.api.Data.MySQL.max_connection_lifetime:type_name -> google.protobuf.Duration
	0,  // 14: kratos.api.Telemetry.Tracing.protocol:type_name -> kratos.api.Telemetry.Protocol
	0,  // 15: kratos.api.Telemetry.Metrics.protocol:type_name -> kratos.api.Telemetry.Protocol
	13, // 16: kratos.api.Telemetry.Metrics.export_interval:type_name -> google.protobuf.Duration
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	file_conf_conf_proto_msgTypes[8].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[10].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
