syntax = "proto3";

package velony.asset.api.v1;

import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "google/api/httpbody.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/velonyapp/asset/gen/api/v1;apiv1";

service AssetService {
  rpc PresignImage(PresignImageRequest)
  returns (PresignImageResponse) {
    option (google.api.http) = {
      post: "/v1:presignImage"
      body: "*"
    };
  }

  rpc UploadImage(UploadImageRequest)
  returns (UploadImageResponse) {
    option (google.api.http) = {
      post: "/v1:uploadImage"
      body: "image"
    };
  }

  rpc RemoveImage(RemoveImageRequest)
  returns (RemoveImageResponse) {
    option (google.api.http) = {
      post: "/v1:removeImage"
      body: "*"
    };
  }
}

enum ImageResizeFit {
  IMAGE_RESIZE_FIT_UNSPECIFIED = 0;

  IMAGE_RESIZE_FIT_CONTAIN = 1;
  IMAGE_RESIZE_FIT_COVER   = 2;
  IMAGE_RESIZE_FIT_PAD     = 3;
  IMAGE_RESIZE_FIT_STRETCH = 4;
}

enum ImageGravity {
  IMAGE_GRAVITY_UNSPECIFIED = 0;

  IMAGE_GRAVITY_CENTER       = 1;
  IMAGE_GRAVITY_TOP          = 2;
  IMAGE_GRAVITY_TOP_RIGHT    = 3;
  IMAGE_GRAVITY_RIGHT        = 4;
  IMAGE_GRAVITY_BOTTOM_RIGHT = 5;
  IMAGE_GRAVITY_BOTTOM       = 6;
  IMAGE_GRAVITY_BOTTOM_LEFT  = 7;
  IMAGE_GRAVITY_LEFT         = 8;
  IMAGE_GRAVITY_TOP_LEFT     = 9;
}

enum ImageFormat {
  IMAGE_FORMAT_UNSPECIFIED = 0;

  IMAGE_FORMAT_JPEG = 1;
  IMAGE_FORMAT_PNG  = 2;
  IMAGE_FORMAT_WEBP = 3;
  IMAGE_FORMAT_AVIF = 4;
}

message ImageResize {
  optional uint32 width = 1 [
    (google.api.field_behavior) = OPTIONAL
  ];
  optional uint32 height = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];

  ImageResizeFit fit = 3 [
    (google.api.field_behavior) = OPTIONAL
  ];

  ImageGravity gravity = 4 [
    (google.api.field_behavior) = OPTIONAL
  ];

  optional string background_color = 5 [
    (google.api.field_behavior) = OPTIONAL
  ];

  bool allow_upscale = 6 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message ImageEncoding {
  ImageFormat format = 1 [
    (google.api.field_behavior) = OPTIONAL
  ];

  optional uint32 quality = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message ImageTransform {
  ImageResize resize = 1 [
    (google.api.field_behavior) = OPTIONAL
  ];

  ImageEncoding encoding = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message PresignImageRequest {
  string storage_key = 1 [
    (google.api.field_behavior) = REQUIRED
  ];

  ImageTransform transform = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];

  google.protobuf.Timestamp expire_time = 3 [
    (google.api.field_behavior) = REQUIRED
  ];
}

message PresignImageResponse {
  string upload_url = 1;
}

message UploadImageRequest {
  string token = 1 [
    (google.api.field_behavior) = REQUIRED
  ];

  google.api.HttpBody image = 2 [
    (google.api.field_behavior) = REQUIRED
  ];
}

message UploadImageResponse {
  string storage_key = 1;
}

message RemoveImageRequest {
  string storage_key = 1 [
    (google.api.field_behavior) = REQUIRED
  ];
}

message RemoveImageResponse {}