syntax = "proto3";

package velony.asset.api.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/api/client.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/velonyapp/asset/gen/api/v1;apiv1";

service AssetService {
  option (google.api.default_host) = "api.velony.app";

  rpc GetImage(GetImageRequest) returns (Image) {
    option (google.api.http) = {
      get: "/v1/{name=images/*}"
    };
    option (google.api.method_signature) = "name";
  }

  rpc CreateImage(CreateImageRequest) returns (Image) {
    option (google.api.http) = {
      post: "/v1/images"
      body: "image"
    };
    option (google.api.method_signature) = "image";
  }

  rpc PresignImage(PresignImageRequest)
  returns (PresignImageResponse) {
    option (google.api.http) = {
      post: "/v1/{name=images/*}:presign"
      body: "*"
    };
  }

  rpc ReconcileImage(ReconcileImageRequest)
  returns (ReconcileImageResponse) {
    option (google.api.http) = {
      post: "/v1/{name=images/*}:reconcile"
      body: "*"
    };
  }

  rpc ProcessImage(ProcessImageRequest)
  returns (ProcessImageResponse) {
    option (google.api.http) = {
      post: "/v1/{name=images/*}:process"
      body: "*"
    };
  }

  rpc DeleteImage(DeleteImageRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=images/*}"
    };
    option (google.api.method_signature) = "name";
  }
}

enum ImageResizeFit {
  IMAGE_RESIZE_FIT_UNSPECIFIED = 0;

  CONTAIN = 1;
  COVER   = 2;
  PAD     = 3;
  STRETCH = 4;
}

enum ImageGravity {
  IMAGE_GRAVITY_UNSPECIFIED = 0;

  CENTER       = 1;
  TOP          = 2;
  TOP_RIGHT    = 3;
  RIGHT        = 4;
  BOTTOM_RIGHT = 5;
  BOTTOM       = 6;
  BOTTOM_LEFT  = 7;
  LEFT         = 8;
  TOP_LEFT     = 9;
}

enum ImageFormat {
  IMAGE_FORMAT_UNSPECIFIED = 0;

  JPEG = 1;
  PNG  = 2;
  WEBP = 3;
  AVIF = 4;
}

message ImageResize {
  optional uint32 width = 1 [
    (google.api.field_behavior) = OPTIONAL
  ];
  optional uint32 height = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];

  ImageResizeFit fit = 3 [
    (google.api.field_behavior) = OPTIONAL
  ];

  ImageGravity gravity = 4 [
    (google.api.field_behavior) = OPTIONAL
  ];

  optional string background_color = 5 [
    (google.api.field_behavior) = OPTIONAL
  ];

  bool allow_upscale = 6 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message ImageEncoding {
  ImageFormat format = 1 [
    (google.api.field_behavior) = OPTIONAL
  ];

  optional uint32 quality = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message Image {
  option (google.api.resource) = {
    type    : "api.velony.app/Image"
    pattern : "images/{image}"
    singular: "image"
    plural  : "images"
  };

  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  repeated string tags = 2 [(google.api.field_behavior) = REQUIRED];

  string object_key    = 3 [(google.api.field_behavior) = REQUIRED];
  bool   object_exists = 4 [(google.api.field_behavior) = OUTPUT_ONLY];

  google.protobuf.Timestamp create_time = 5 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message GetImageRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "api.velony.app/Image"
    }
  ];
}

message CreateImageRequest {
  Image image = 1 [(google.api.field_behavior) = REQUIRED];
}

message PresignImageRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "api.velony.app/Image"
    }
  ];

  google.protobuf.Duration ttl = 2 [
    (buf.validate.field).duration.gt = {}
  ];
}

message PresignImageResponse {
  string upload_url = 1;
}

message ProcessImageRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "api.velony.app/Image"
    }
  ];

  ImageResize resize = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
  ImageEncoding encoding = 3 [
    (google.api.field_behavior) = OPTIONAL
  ];
  bool auto_rotate = 4 [
    (google.api.field_behavior) = OPTIONAL
  ];
  bool remove_metadata = 5 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message ProcessImageResponse {}

message ReconcileImageRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "api.velony.app/Image"
    }
  ];
}

message ReconcileImageResponse {
  Image image = 1;
}

message DeleteImageRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "api.velony.app/Image"
    }
  ];
}
