// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/velonyapp/asset/internal/application/command"
	"github.com/velonyapp/asset/internal/application/domainevent"
	"github.com/velonyapp/asset/internal/application/query"
	"github.com/velonyapp/asset/internal/conf"
	"github.com/velonyapp/asset/internal/infrastructure/data/mysql"
	"github.com/velonyapp/asset/internal/infrastructure/data/s3"
	"github.com/velonyapp/asset/internal/infrastructure/messaging/protobuf"
	"github.com/velonyapp/asset/internal/infrastructure/processing"
	"github.com/velonyapp/asset/internal/presentation/api"
	"github.com/velonyapp/asset/internal/presentation/middleware"
	"github.com/velonyapp/asset/internal/presentation/transport"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(data *conf.Data, confTransport *conf.Transport, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	encoder := protobuf.NewEncoder()
	eventPublisher := mysql.NewEventPublisher(db, encoder)
	imageCreatedHandler := domainevent.NewImageCreatedHandler(eventPublisher)
	imageObjectExistenceUpdatedHandler := domainevent.NewImageObjectExistenceUpdatedHandler(eventPublisher)
	imageDeletedHandler := domainevent.NewImageDeletedHandler(eventPublisher)
	dispatcher := domainevent.NewDispatcher(imageCreatedHandler, imageObjectExistenceUpdatedHandler, imageDeletedHandler)
	image := mysql.NewImageRepo(db, dispatcher)
	unitOfWork := mysql.NewUnitOfWork(db)
	createImageHandler := command.NewCreateImageHandler(image, unitOfWork)
	client, err := s3.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	storage := s3.NewStorage(client, data)
	imageProcessor := processing.NewImageProcessor()
	processImageHandler := command.NewProcessImageHandler(image, eventPublisher, storage, imageProcessor)
	reconcileImageHandler := command.NewReconcileImageHandler(image, unitOfWork, storage)
	deleteImageHandler := command.NewDeleteImageHandler(image, unitOfWork, storage)
	handlerRegistry := command.NewHandlerRegistry(createImageHandler, processImageHandler, reconcileImageHandler, deleteImageHandler)
	getImageHandler := query.NewGetImageHandler(image)
	presignImageHandler := query.NewPresignImageHandler(image, storage)
	queryHandlerRegistry := query.NewHandlerRegistry(getImageHandler, presignImageHandler)
	service := api.NewService(handlerRegistry, queryHandlerRegistry)
	tracing := middleware.NewTracing()
	metrics, err := middleware.NewMetrics()
	if err != nil {
		return nil, nil, err
	}
	errorMapper := middleware.NewErrorMapper()
	validation := middleware.NewValidation()
	server := transport.NewGRPCServer(confTransport, service, tracing, metrics, errorMapper, validation)
	httpServer := transport.NewHTTPServer(confTransport, service, tracing, metrics, errorMapper, validation)
	rabbitMQConsumer := transport.NewRabbitMQConsumer(handlerRegistry, confTransport)
	app := newApp(logger, server, httpServer, rabbitMQConsumer)
	return app, func() {
	}, nil
}
