// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/velonyapp/asset/internal/application/command"
	"github.com/velonyapp/asset/internal/application/domainevent"
	"github.com/velonyapp/asset/internal/application/query"
	"github.com/velonyapp/asset/internal/conf"
	"github.com/velonyapp/asset/internal/info"
	"github.com/velonyapp/asset/internal/infrastructure/data/mysql"
	"github.com/velonyapp/asset/internal/infrastructure/data/s3"
	"github.com/velonyapp/asset/internal/infrastructure/event"
	"github.com/velonyapp/asset/internal/infrastructure/image"
	observability2 "github.com/velonyapp/asset/internal/infrastructure/observability"
	"github.com/velonyapp/asset/internal/presentation/api"
	"github.com/velonyapp/asset/internal/presentation/observability"
	"github.com/velonyapp/asset/internal/presentation/transport"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, service *info.Service, data *conf.Data, confTransport *conf.Transport, confObservability *conf.Observability, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	encoder := event.NewEncoder()
	eventPublisher := mysql.NewEventPublisher(db, encoder)
	imageCreatedHandler := domainevent.NewImageCreatedHandler(eventPublisher)
	imageObjectExistenceUpdatedHandler := domainevent.NewImageObjectExistenceUpdatedHandler(eventPublisher)
	imageDeletedHandler := domainevent.NewImageDeletedHandler(eventPublisher)
	dispatcher := domainevent.NewDispatcher(imageCreatedHandler, imageObjectExistenceUpdatedHandler, imageDeletedHandler)
	repoImage := mysql.NewImageRepo(db, dispatcher)
	unitOfWork := mysql.NewUnitOfWork(db)
	createImageHandler := command.NewCreateImageHandler(repoImage, unitOfWork)
	client, err := s3.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	storage := s3.NewStorage(client, data)
	imageProcessor := image.NewProcessor()
	processImageHandler := command.NewProcessImageHandler(repoImage, eventPublisher, storage, imageProcessor)
	reconcileImageHandler := command.NewReconcileImageHandler(repoImage, unitOfWork, storage)
	deleteImageHandler := command.NewDeleteImageHandler(repoImage, unitOfWork, storage)
	handlerRegistry := command.NewHandlerRegistry(createImageHandler, processImageHandler, reconcileImageHandler, deleteImageHandler)
	getImageHandler := query.NewGetImageHandler(repoImage)
	presignImageHandler := query.NewPresignImageHandler(repoImage, storage)
	queryHandlerRegistry := query.NewHandlerRegistry(getImageHandler, presignImageHandler)
	apiService := api.NewService(handlerRegistry, queryHandlerRegistry)
	serverMetrics, err := observability.NewServerMetrics()
	if err != nil {
		return nil, nil, err
	}
	server := transport.NewGRPCServer(confTransport, apiService, serverMetrics)
	httpServer := transport.NewHTTPServer(confTransport, apiService, serverMetrics)
	rabbitMQConsumer := transport.NewRabbitMQConsumer(handlerRegistry, confTransport)
	openTelemetry, cleanup, err := observability2.NewOpenTelemetry(contextContext, confObservability, service)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, server, httpServer, rabbitMQConsumer, openTelemetry)
	return app, func() {
		cleanup()
	}, nil
}
